name: Build and Push Docker Image to GitHub

on:
  push:
    branches: ["main"]
    tags: v*

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker tag
        id: docker-tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build and push latest
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: alexankoh/app_for_practice:latest

      - name: Build and push versioned
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            alexankoh/app_for_practice:${{ steps.docker-tag.outputs.tag }}
            alexankoh/app_for_practice:latest
